### ISSUE TITLE
Make easier creating a new file

### ISSUE THREAD

**Issue by ravem** [Xed-Editor/Xed-Editor#126]
**Is your feature request related to a problem? Please describe.**
Creating a new file is somewhat tricky

**Describe the solution you'd like**

As far as I have seen, to start editing a new file, at the moment, you should:

- create a new file
- refresh the folder view (or it doesn't appear) 
- then start the edit

This process is too complicated for a quick use, at least for me.

It would be easier if the main screen is already in editing mode when the software is opened, so to speed up starting to work on a new file.
Another way to make the things easier could be to have the chance, in the opening screen, to choose between "Open File or Folder" and "Create a new file".

**Comment by RohitKushvaha01** [comment]
> ## Add
> - Folder Manager
> > It is very helpful for creating file/delete file/move/replication/search.
> -  Recursive Search String
> > File name to find (support `*` )
> Text to find
> Match case
> ---
> ![Screenshot_20240908-123602](https://github.com/user-attachments/assets/eb3ab589-530f-4ff9-a857-416fae5eca67)
> 
> 
> 

Can you explain this in details
