### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by risky777** [Xed-Editor/Xed-Editor#183]
**Describe the bug**
I already wrote about this, but xed seemed like alpha-stage project at that time so I gave up.

In word wrap, end of line goes may go beyond edge of screen and so it is invisible.

**Screenshots**
![Screenshot_20240819-150022](https://github.com/user-attachments/assets/4f33a2b5-3b9f-4a94-a58a-dfc208c9035f)

Test text:
[testing.txt](https://github.com/user-attachments/files/17276761/testing.txt)

**complete the following information):**
 - Blackview Tab12 (tablet 10")
 - Android 11

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> I already wrote about this, but xed seemed like alpha-stage project at that time so I gave up.
> 
> In word wrap, end of line goes may go beyond edge of screen and so it is invisible.
> 
> **Screenshots**
> ![Screenshot_20240819-150022](https://github.com/user-attachments/assets/4f33a2b5-3b9f-4a94-a58a-dfc208c9035f)
> 
> Test text:
> [testing.txt](https://github.com/user-attachments/files/17276761/testing.txt)
> 
> **complete the following information):**
>  - Blackview Tab12 (tablet 10")
>  - Android 11

Have you tried to reproduce this bug on a different device?

**Comment by risky777** [comment]
It's only android tablet I have, so no other device. Besides, acode and code-editor don't have this issue (but have others so I'm still looking for something like geany-linux that just works).

**Comment by RohitKushvaha01** [comment]
Relevant resources
https://github.com/davidmoten/word-wrap

**Comment by trindadedev13** [comment]
Apparently, it's a Tablet-only issue, I tried it on my phone in landscape mode, and it doesn't happen.

**Comment by RohitKushvaha01** [comment]
@risky777 try this commit build https://github.com/Xed-Editor/Xed-Editor/actions/runs/11624900893
