### ISSUE TITLE
Can't switch input language

### ISSUE THREAD

**Issue by KirkSuD** [Xed-Editor/Xed-Editor#189]
**Describe the bug**
After upgrading to v2.7.3, when I press the language switch button on Gboard,  
it would only switch between "Qwerty" & "English". I can't switch to other languages.

**To Reproduce**
1. Open any file.
2. Click language switch button on Gboard.
3. The language is always Qwerty or English.

**Expected behavior**
Able to type in other languages.

**complete the following information):**
 - Device: POCO M3 Pro 5G
 - OS: MIUI Global 14.0.3
 - Android Version: Android 13

**Additional context**
I installed Karbon from F-droid.  
Are there some options / config needed to be set?

It's similar to [this Acode issue](https://github.com/deadlyjack/Acode/issues/882#issuecomment-2027319734).

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** After upgrading to v2.7.3, when I press the language switch button on Gboard, it would only switch between "Qwerty" & "English". I can't switch to other languages.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open any file.
> 2. Click language switch button on Gboard.
> 3. The language is always Qwerty or English.
> 
> **Expected behavior** Able to type in other languages.
> 
> **complete the following information):**
> 
> * Device: POCO M3 Pro 5G
> * OS: MIUI Global 14.0.3
> * Android Version: Android 13
> 
> **Additional context** I installed Karbon from F-droid. Are there some options / config needed to be set?
> 
> It's similar to [this Acode issue](https://github.com/deadlyjack/Acode/issues/882#issuecomment-2027319734).

to be able to switch languages you need to enable text suggestions

**Comment by KirkSuD** [comment]
Sorry, I don't get it.  
I didn't find text suggestions option in Karbon's settings.  
In my Gboard settings > Text correction > Suggestions,  
"Show suggestion strip" & "Next-word suggestions" options are enabled.

I think the language is switched, but Qwerty keyboard layout is still used by Gboard,  
when non-English languages are selected. [Here's a screenshot](https://i.imgur.com/mNZw5i8.jpeg).

I can type in other languages when these 2 lines are commented out:
https://github.com/Xed-Editor/Xed-Editor/blob/57ce34c7cf1695942a30b202384df1a0dbd4a39e/app/src/main/java/com/rk/xededitor/MainActivity/editor/TabFragment.kt#L52-L53

So maybe it's related to inputType.
Maybe [TYPE_TEXT_FLAG_NO_SUGGESTIONS](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_FLAG_NO_SUGGESTIONS) makes Gboard use the Qwerty keyboard?
Thank you. 🙏

**Comment by RohitKushvaha01** [comment]
> Sorry, I don't get it.  
> I didn't find text suggestions option in Karbon's settings.  
> In my Gboard settings > Text correction > Suggestions,  
> "Show suggestion strip" & "Next-word suggestions" options are enabled.
> 
> I think the language is switched, but Qwerty keyboard layout is still used by Gboard,  
> when non-English languages are selected. [Here's a screenshot](https://i.imgur.com/mNZw5i8.jpeg).
> 
> I can type in other languages when these 2 lines are commented out:
> https://github.com/Xed-Editor/Xed-Editor/blob/57ce34c7cf1695942a30b202384df1a0dbd4a39e/app/src/main/java/com/rk/xededitor/MainActivity/editor/TabFragment.kt#L52-L53
> 
> So maybe it's related to inputType?
> Thank you. 🙏

Download the latest commit then go to 
Settings > Editor then scroll down and enable text suggestions

**Comment by KirkSuD** [comment]
Oh, I see. The latest commit works. Thanks.
