### ISSUE TITLE
Runner not available

### ISSUE THREAD

**Issue by Brajesh3** [Xed-Editor/Xed-Editor#190]
**Describe the bug**
Runner option not available instantly

**To Reproduce**
1. Go to file manager
2. Click on any markdown, html or python file
3. Runner option not available

**Expected behavior**
Runner option available

**Screenshots**
![Screenshot_20241008-233802_Karbon](https://github.com/user-attachments/assets/2a743e5c-5d13-433a-93d9-89fc2fc620f4)

**complete the following information):**
 - Device: Samsung M11
 - OS: One UI 4.1
 - Android Version 12

**logcat output/logcat.txt(if applicable)**
n/a

**Additional context**
n/a

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> Runner option not available instantly
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to file manager
> 2. Click on any markdown, html or python file
> 3. Runner option not available
> 
> **Expected behavior**
> Runner option available
> 
> **Screenshots**
> ![Screenshot_20241008-233802_Karbon](https://github.com/user-attachments/assets/2a743e5c-5d13-433a-93d9-89fc2fc620f4)
> 
> 
> **complete the following information):**
>  - Device: Samsung M11
>  - OS: One UI 4.1
>  - Android Version 12
> 
> **logcat output/logcat.txt(if applicable)**
> n/a
> 
> **Additional context**
> n/a
> 

Runners are not available in the external editor for now
