### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by HallowedSpace** [Xed-Editor/Xed-Editor#224]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
Unix Time : 1728687300689
LocalTime : Oct 11, 2024 6:55:00 PM

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = SM-S908U
SEM_INT = 3402
SECURITY_PATCH = 2024-09-01
BASE_OS = 
SEM_FIRST_SDK_INT = 31
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150500
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = S908USQU6EXH8

Error Message : java.lang.String cannot be cast to java.lang.Boolean
Error Cause : null
Error StackTrace : 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e0838e3, Dispatchers.Default]

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
> Unix Time : 1728687300689
> LocalTime : Oct 11, 2024 6:55:00 PM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = SM-S908U
> SEM_INT = 3402
> SECURITY_PATCH = 2024-09-01
> BASE_OS = 
> SEM_FIRST_SDK_INT = 31
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> SEM_PLATFORM_INT = 150500
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = S908USQU6EXH8
> 
> 
> Error Message : java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
> 	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
> 	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
> 	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
> 	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e0838e3, Dispatchers.Default]
> 

Clear app data to fix the issue
