### ISSUE TITLE
Run button is broken

### ISSUE THREAD

**Issue by GitAlasGo** [Xed-Editor/Xed-Editor#250]
**Describe the bug**
The run button doesn't appear sometimes.

**Screenshots**
[With run button](https://imgur.com/a/gLLuvMp)
[Without run button](https://imgur.com/a/K6VvunK)

**To Reproduce**
1. Open the app
2. Click on a file that ends with **.md**
3. Look if there's a run button

**Expected behavior**
There should be a run button at all times.

I'm on a Android 11 and using a phone from china.

**Comment by trindadedev13** [comment]
It works for me

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** The run button doesn't appear sometimes.
> 
> **Screenshots** [With run button](https://imgur.com/a/gLLuvMp) [Without run button](https://imgur.com/a/K6VvunK)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open the app
> 2. Click on a file that ends with **.md**
> 3. Look if there's a run button
> 
> **Expected behavior** There should be a run button at all times.
> 
> I'm on a Android 11 and using a phone from china.

this issue is already fixed, what commit build you are using?
