### ISSUE TITLE
[Crash Report] Karbon crashed when trying open/load a 185 KiB text file.

### ISSUE THREAD

**Issue by sripadks** [Xed-Editor/Xed-Editor#255]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1729665097911
LocalTime : 23-Oct-2024 12:01:37 pm

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = A063
SECURITY_PATCH = 2024-09-01
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Nothing
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = Nothing
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 2409041634

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3973)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:66)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1476)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1729665097911
> LocalTime : 23-Oct-2024 12:01:37 pm
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = A063
> SECURITY_PATCH = 2024-09-01
> BASE_OS = 
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Nothing
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> brand = Nothing
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 2409041634
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3973)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:232)
> 	at android.os.Looper.loop(Looper.java:334)
> 	at android.app.ActivityThread.main(ActivityThread.java:8291)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
> 	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:66)
> 	at android.app.Activity.performCreate(Activity.java:8595)
> 	at android.app.Activity.performCreate(Activity.java:8573)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1476)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
> 	... 12 more
> 

Clear app data to fix the issue
