### ISSUE TITLE
Crash report: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized

### ISSUE THREAD

**Issue by hushenghao** [Xed-Editor/Xed-Editor#256]
**To Reproduce**
1. Turn off network connection 
2. Go to 'Terminal'
3. See error

**logcat output/logcat.txt(if applicable)**

```log
Fatal Crash occurred on Thread named 'main'
Unix Time : 1729736446759
LocalTime : 2024年10月24日 10:20:46

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = MEIZU 18X
SECURITY_PATCH = 2024-03-05
BASE_OS = 
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = meizu
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = meizu
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 1686879531


Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error StackTrace : 

java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5514)
 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5547)
 at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2354)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:8068)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
 at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
 at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
 at android.app.Activity.performDestroy(Activity.java:8582)
 at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1424)
 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5501)
 ... 13 more
```

**Comment by RohitKushvaha01** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Turn off network connection 
> 2. Go to 'Terminal'
> 3. See error
> 
> **logcat output/logcat.txt(if applicable)**
> 
> ```log
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1729736446759
> LocalTime : 2024年10月24日 10:20:46
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = MEIZU 18X
> SECURITY_PATCH = 2024-03-05
> BASE_OS = 
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = meizu
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> brand = meizu
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 1686879531
> 
> 
> Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
>  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5514)
>  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5547)
>  at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
>  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
>  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
>  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
>  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2354)
>  at android.os.Handler.dispatchMessage(Handler.java:106)
>  at android.os.Looper.loopOnce(Looper.java:201)
>  at android.os.Looper.loop(Looper.java:288)
>  at android.app.ActivityThread.main(ActivityThread.java:8068)
>  at java.lang.reflect.Method.invoke(Native Method)
>  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
>  at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
>  at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
>  at android.app.Activity.performDestroy(Activity.java:8582)
>  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1424)
>  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5501)
>  ... 13 more
> ```
> 
> 

Already fixed in 2.7.4
