### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AliAkrem** [Xed-Editor/Xed-Editor#274]
Fatal Crash occurred on Thread named 'Thread-7'
Unix Time : 1730502388906
LocalTime : 2 Nov 2024 00:06:28

ALL_CODENAMES = [REL]
ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = SM-J410F
RESOURCES_SDK_INT = 27
SECURITY_PATCH = 2020-12-01
BASE_OS = samsung/j4coreltejx/j4corelte:8.1.0/M1AJB/J410FXXU2ASL5:user/release-keys
RELEASE = 8.1.0
CODENAME = REL
manufacturer = samsung
SECURITY_INDEX = 2
SDK_INT = 27
PREVIEW_SDK_INT = 0
SDK = 27
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = J410FXXS2AVK2

Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:764)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-7'
> Unix Time : 1730502388906
> LocalTime : 2 Nov 2024 00:06:28
> 
> ALL_CODENAMES = [REL]
> ACTIVE_CODENAMES = []
> app_version = 2.6.0
> device_model = SM-J410F
> RESOURCES_SDK_INT = 27
> SECURITY_PATCH = 2020-12-01
> BASE_OS = samsung/j4coreltejx/j4corelte:8.1.0/M1AJB/J410FXXU2ASL5:user/release-keys
> RELEASE = 8.1.0
> CODENAME = REL
> manufacturer = samsung
> SECURITY_INDEX = 2
> SDK_INT = 27
> PREVIEW_SDK_INT = 0
> SDK = 27
> brand = samsung
> supported_abi = [armeabi-v7a,armeabi]
> INCREMENTAL = J410FXXS2AVK2
> 
> 
> Error Message : listFiles(...) must not be null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException: listFiles(...) must not be null
> 	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at java.lang.Thread.run(Thread.java:764)
> 

You are using ancient version. Update to v2.7.3 or v2.7.4
