### ISSUE TITLE
USING TERMUX WHICH IS UNDER GPL!!

### ISSUE THREAD

**Issue by MohammedKHC0** [Xed-Editor/Xed-Editor#286]
Hello, I have seen this project and it looks promising, but please note that termux is licensed under GPL, which requires that any derivative work be licensed under GPL!, which is not the case with this project, so either you license this project under GPL, or remove termux. And use something like jackpal Terminal Emulator, which termux is based on, But it's not maintenaned anymore.

**Comment by RohitKushvaha01** [comment]
> Hello, I have seen this project and it looks promising, but please note that termux is licensed under GPL, which requires that any derivative work be licensed under GPL!, which is not the case with this project, so either you license this project under GPL, or remove termux. And use something like jackpal Terminal Emulator, which termux is based on, But it's not maintenaned anymore.

Termux view library is licensed under GPL
![Screenshot_20241106-164440.jpg](https://github.com/user-attachments/assets/83b919f1-a189-4088-992a-34b25deb5941)
