### ISSUE TITLE
F-Droid can't build and opt-out updater

### ISSUE THREAD

**Issue by licaon-kter** [Xed-Editor/Xed-Editor#287]
ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8282421295#L792

diff log:
```
│ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/BuildConfig.smali
│ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/BuildConfig.smali
│ │ │ │ │ @@ -10,15 +10,15 @@
│ │ │ │ │  
│ │ │ │ │  .field public static final DEBUG:Z = false
│ │ │ │ │  
│ │ │ │ │  .field public static final GIT_COMMIT_DATE:Ljava/lang/String; = "2024-11-06T13:10:53+05:30"
│ │ │ │ │  
│ │ │ │ │  .field public static final GIT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8fe1352e953655d5fb504e4ae79475746b5"
│ │ │ │ │  
│ │ │ │ │ -.field public static final GIT_SHORT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8f"
│ │ │ │ │ +.field public static final GIT_SHORT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8fe"
│ │ │ │ │  
│ │ │ │ │  .field public static final VERSION_CODE:I = 0x23
│ │ │ │ │  
│ │ │ │ │  .field public static final VERSION_NAME:Ljava/lang/String; = "2.8.0"
│ │ │ │ │  
│ │ │ │ │  
│ │ │ │ │  # direct methods
│ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui
│ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui
│ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens
│ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens
│ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings
│ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings
│ │ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings/about
│ │ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings/about
│ │ │ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings/about/ComposableSingletons$AboutScreenKt$lambda-4$1.smali
│ │ │ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings/about/ComposableSingletons$AboutScreenKt$lambda-4$1.smali
│ │ │ │ │ │ │ │ │ @@ -144,15 +144,15 @@
│ │ │ │ │ │ │ │ │      move-result-object v22
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      const/16 v25, 0x0
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      const v26, 0xfffe
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      .line 50
│ │ │ │ │ │ │ │ │ -    const-string v2, "5cdfd8f"
│ │ │ │ │ │ │ │ │ +    const-string v2, "5cdfd8fe"
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      const/4 v3, 0x0
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      const-wide/16 v4, 0x0
│ │ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │ │      const-wide/16 v6, 0x0
```

also since  https://github.com/Xed-Editor/Xed-Editor/commit/4f40be2170a9633ae6a0b4677c2442d82c59450f#diff-85565ed3059bc3492484e4668fede57064ecc719997e3330bb1e1fe7388cd325 you added an update checker that's opt-out?

that's not allowed in F-Droid, can it be made opt-in? 

Also try/catch this fail if github is not accessible:
```
java.net.SocketTimeoutException: failed to connect to api.github.com/140.82.121.6 (port 443) from /10.1.10.1 (port 42778) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.rk.xededitor.update.UpdateManager$fetch$1.invokeSuspend(UpdateManager.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@54eac0, Dispatchers.IO]
```

**Comment by RohitKushvaha01** [comment]
> ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8282421295#L792
> 
> diff log:
> 
> ```
> │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/BuildConfig.smali
> │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/BuildConfig.smali
> │ │ │ │ │ @@ -10,15 +10,15 @@
> │ │ │ │ │  
> │ │ │ │ │  .field public static final DEBUG:Z = false
> │ │ │ │ │  
> │ │ │ │ │  .field public static final GIT_COMMIT_DATE:Ljava/lang/String; = "2024-11-06T13:10:53+05:30"
> │ │ │ │ │  
> │ │ │ │ │  .field public static final GIT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8fe1352e953655d5fb504e4ae79475746b5"
> │ │ │ │ │  
> │ │ │ │ │ -.field public static final GIT_SHORT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8f"
> │ │ │ │ │ +.field public static final GIT_SHORT_COMMIT_HASH:Ljava/lang/String; = "5cdfd8fe"
> │ │ │ │ │  
> │ │ │ │ │  .field public static final VERSION_CODE:I = 0x23
> │ │ │ │ │  
> │ │ │ │ │  .field public static final VERSION_NAME:Ljava/lang/String; = "2.8.0"
> │ │ │ │ │  
> │ │ │ │ │  
> │ │ │ │ │  # direct methods
> │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui
> │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui
> │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens
> │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens
> │ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings
> │ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings
> │ │ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings/about
> │ │ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings/about
> │ │ │ │ │ │ │ │ │   --- xed-editor-v2.8.0/smali_classes4/com/rk/xededitor/ui/screens/settings/about/ComposableSingletons$AboutScreenKt$lambda-4$1.smali
> │ │ │ │ │ │ │ │ ├── +++ com.rk.xededitor_35/smali_classes4/com/rk/xededitor/ui/screens/settings/about/ComposableSingletons$AboutScreenKt$lambda-4$1.smali
> │ │ │ │ │ │ │ │ │ @@ -144,15 +144,15 @@
> │ │ │ │ │ │ │ │ │      move-result-object v22
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      const/16 v25, 0x0
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      const v26, 0xfffe
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      .line 50
> │ │ │ │ │ │ │ │ │ -    const-string v2, "5cdfd8f"
> │ │ │ │ │ │ │ │ │ +    const-string v2, "5cdfd8fe"
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      const/4 v3, 0x0
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      const-wide/16 v4, 0x0
> │ │ │ │ │ │ │ │ │  
> │ │ │ │ │ │ │ │ │      const-wide/16 v6, 0x0
> ```
> 
> also since [4f40be2#diff-85565ed3059bc3492484e4668fede57064ecc719997e3330bb1e1fe7388cd325](https://github.com/Xed-Editor/Xed-Editor/commit/4f40be2170a9633ae6a0b4677c2442d82c59450f#diff-85565ed3059bc3492484e4668fede57064ecc719997e3330bb1e1fe7388cd325) you added an update checker that's opt-out?
> 
> that's not allowed in F-Droid, can it be made opt-in?
> 
> Also try/catch this fail if github is not accessible:
> 
> ```
> java.net.SocketTimeoutException: failed to connect to api.github.com/140.82.121.6 (port 443) from /10.1.10.1 (port 42778) after 10000ms
> 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
> 	at libcore.io.IoBridge.connect(IoBridge.java:179)
> 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
> 	at java.net.Socket.connect(Socket.java:646)
> 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
> 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
> 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
> 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
> 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at com.rk.xededitor.update.UpdateManager$fetch$1.invokeSuspend(UpdateManager.kt:51)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@54eac0, Dispatchers.IO]
> ```

Thank you for raising the issue. I’ve addressed the Git commit hash length discrepancy, as I wasn’t aware that Git can generate varying hash lengths. I’ve also opted out of the update checker functionality. The update checker is designed solely to notify users of new commits since their installed version; it doesn’t download or update the app itself. Additionally, I resolved a crash in the update checker, which only occurred on fresh installs, making it harder to identify initially.

**Comment by RohitKushvaha01** [comment]
@licaon-kter I also recreated the release just in case.
