### ISSUE TITLE
Last word of line incorrectly wrapped

### ISSUE THREAD

**Issue by GiovanniSalmeri** [Xed-Editor/Xed-Editor#291]
**Describe the bug**
When word-wrap is active, the last word of a logical line is incorrectly put in a new line even if there is space in the previous line. All works as intended if a trailing space is added.

**To Reproduce**
1. Set word-wrap.
2. Write a long line.

**Expected behavior**
The last word should not be put in a new line unless necessary.

**Screenshots**
[See `magical / creatures`](https://github.com/Xed-Editor/Xed-Editor/blob/main/fastlane/metadata/android/en-US/images/phoneScreenshots/02.jpg)

**complete the following information):**
 - Device: Xiami POCO C65
 - OS: MIUI 14
 - Android Version: 13

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** When word-wrap is active, the last word of a logical line is incorrectly put in a new line even if there is space in the previous line. All works as intended if a trailing space is added.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Set word-wrap.
> 2. Write a long line.
> 
> **Expected behavior** The last word should not be put in a new line unless necessary.
> 
> **Screenshots** [See `magical / creatures`](https://github.com/Xed-Editor/Xed-Editor/blob/main/fastlane/metadata/android/en-US/images/phoneScreenshots/02.jpg)
> 
> **complete the following information):**
> 
> * Device: Xiami POCO C65
> * OS: MIUI 14
> * Android Version: 13

This is intended behavior. It exists because, when you scroll down, a scrollbar will appear. To prevent words from being hidden by the scrollbar, some space is reserved for it. This was implemented intentionally.
