### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Luis886t** [Xed-Editor/Xed-Editor#296]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
Unix Time : 1731479212059
LocalTime : 13 nov 2024 12:26:52 a. m.

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = SM-A135M
SEM_INT = 3401
SECURITY_PATCH = 2024-10-01
BASE_OS = samsung/a13ub/a13:14/UP1A.231005.007/A135MUBU7DXH1:user/release-keys
SEM_FIRST_SDK_INT = 31
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = A135MUBS8DXJ1

Error Message : com.rk.xededitor has no access to content://media/external/file/1000002787
Error Cause : null
Error StackTrace : 

java.lang.SecurityException: com.rk.xededitor has no access to content://media/external/file/1000002787
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1876)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1574)
	at com.rk.xededitor.SimpleEditor.SimpleEditor$save$1.invokeSuspend(SimpleEditor.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@61bb5d1, Dispatchers.IO]

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
> Unix Time : 1731479212059
> LocalTime : 13 nov 2024 12:26:52 a. m.
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = SM-A135M
> SEM_INT = 3401
> SECURITY_PATCH = 2024-10-01
> BASE_OS = samsung/a13ub/a13:14/UP1A.231005.007/A135MUBU7DXH1:user/release-keys
> SEM_FIRST_SDK_INT = 31
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> SEM_PLATFORM_INT = 150100
> brand = samsung
> supported_abi = [armeabi-v7a,armeabi]
> INCREMENTAL = A135MUBS8DXJ1
> 
> 
> Error Message : com.rk.xededitor has no access to content://media/external/file/1000002787
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.SecurityException: com.rk.xededitor has no access to content://media/external/file/1000002787
> 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
> 	at android.os.Parcel.createException(Parcel.java:3053)
> 	at android.os.Parcel.readException(Parcel.java:3036)
> 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
> 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
> 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
> 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1876)
> 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1574)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor$save$1.invokeSuspend(SimpleEditor.kt:200)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@61bb5d1, Dispatchers.IO]
> 

Update the app
