### ISSUE TITLE
Word wrap inconsistent

### ISSUE THREAD

**Issue by martixy** [Xed-Editor/Xed-Editor#297]
**Describe the bug**
Word wrap creates new lines for no good reason.

**To Reproduce**
1. Take basically any text file with a few paragraphs of text.
For example:
`
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
`

**Expected behavior**
Word wrap only when the next word won't fit on the current line.

**Screenshots**
![Screenshot_20241113-104725_Karbon](https://github.com/user-attachments/assets/d7d74e96-f7c4-47a9-a4f7-cca752d6b952)

Why is the last word on a new line?

**complete the following information):**
 - Device: Xiaomi Mi pad 4 and Samsung Galaxy Note 9
 - OS: Some custom rom on my tablet and OneUI on my phone
 - Android Version 10 and 14

**logcat output/logcat.txt(if applicable)**

**Additional context**
Super promising editor TBH, if only the basics could be fixed. I've been desperately looking for something to replace my previous editor with something that works better. Right now it's trading one text rendering flaw for another. TBH I had given up on finding a good, simple text editor on android. Now I have hope.

**Comment by GitAlasGo** [comment]
> I've been desperately looking for something to replace my previous editor

**Acode editor** is what your looking for.

If you don't like it, there's plugin that can do what you want it to be.

**Karbon editor** doesn't have plugins, and all the unique features that becomes with acode.

If **Acode editor** default theme looks ugly to you, it can be made prettier with a plugin.

If you want a proprietary editor there's **QuickEdit Text Editor** on the playstore.

I have to remind you that these two text editors have been around for DECADES, unlike **karbon editor** that is new to the competition.

**Comment by martixy** [comment]
@GitAlasGo
Acode's too heavy. Quick edit has a text rendering bug for DECADES the developer said will never be fixed. Hence, keep looking. Karbon might be the savior.

**Comment by GitAlasGo** [comment]
> @GitAlasGo Acode's too heavy. Quick edit has a text rendering bug for DECADES the developer said will never be fixed. Hence, keep looking. Karbon might be the savior.

What do you exactly mean by **Acode editor is heavy?**

Can you link the sources to where the **QuickEdit** developer said that he'll not fix the issue of the rendering.

**Karbon editor** as it grows in more features it will also grow in size and become heavy like **acode**.

**Comment by RohitKushvaha01** [comment]
> > @GitAlasGo Acode's too heavy. Quick edit has a text rendering bug for DECADES the developer said will never be fixed. Hence, keep looking. Karbon might be the savior.
> 
> What do you exactly mean by **Acode editor is heavy?**
> 
> Can you link the sources to where the **QuickEdit** developer said that he'll not fix the issue of the rendering.
> 
> **Karbon editor** as it grows in more features it will also grow in size and become heavy like **acode**.

Acode is heavy because it is built on older technology (Cordova) using JavaScript, which inherently limits its performance. Unlike native Android apps like Karbon, it cannot achieve the same level of speed and efficiency.

**Comment by martixy** [comment]
> What do you exactly mean by **Acode editor is heavy?**

Sluggish performance. It won't even scroll smoothly. I consider smooth scrolling a basic "don't make me want to kill myself" feature.

> Can you link the sources to where the **QuickEdit** developer said that he'll not fix the issue of the rendering.

https://xdaforums.com/t/app-4-0-3-quickedit-text-editor.2899385/post-89515347
Oh, and the other editor by the same dev has the same scrolling problem as acode.

**Comment by RohitKushvaha01** [comment]
This issue won't be fixed until the upstream [editor library](https://github.com/Rosemoe/sora-editor) addresses it. I've already opened an issue regarding this, but I don't think it will be resolved anytime soon.

**Comment by martixy** [comment]
Btw, is the tab bug also upstream?

**Comment by GitAlasGo** [comment]
> Btw, is the tab bug also upstream?

Brother just go to this issue https://github.com/Rosemoe/sora-editor/issues/629 and subscribe to the issue to receive notifications when someone comments.

**Comment by RohitKushvaha01** [comment]
> Btw, is the tab bug also upstream?

Unnecessary line breaks are fixed. The upstream editor doesn't use the full screen width on large-screen devices.

**Comment by martixy** [comment]
I asked about this bug:
https://xdaforums.com/t/app-4-0-3-quickedit-text-editor.2899385/post-89488171

It is present in this editor. It is different than the word wrap issue.
But the question is, should I be opening and issue here, or upstream?
