### ISSUE TITLE
Rename file?

### ISSUE THREAD

**Issue by srghma** [Xed-Editor/Xed-Editor#338]
https://github.com/Xed-Editor/Xed-Editor/blob/main/app/src/main/assets/textmate/solarized_drak.json

Should be dark?

**Comment by RohitKushvaha01** [comment]
> https://github.com/Xed-Editor/Xed-Editor/blob/main/app/src/main/assets/textmate/solarized_drak.json
> 
> Should be dark?

That file is not used by karbon
