### ISSUE TITLE
Coq language highlighting 

### ISSUE THREAD

**Issue by srghma** [Xed-Editor/Xed-Editor#339]
xxx.v files should be highlighted

**Comment by srghma** [comment]
Or, is there a way to edit the generated Settings.xml and add to make xxx.v files highlighted as ... rust for example?

**Comment by RohitKushvaha01** [comment]
> Or, is there a way to edit the generated Settings.xml and add to make xxx.v files highlighted as ... rust for example?

If this language has a TextMate bundle or theme, it can be added to Karbon. Alternatively, if its syntax closely resembles Rust, the Rust syntax highlighter can be applied.
