### ISSUE TITLE
This error occurs when third-party software redirects to Karbon.

### ISSUE THREAD

**Issue by Bubble-droid** [Xed-Editor/Xed-Editor#341]
After clicking back, editing is possible, but syntax highlighting is not enabled.

``` 
Fatal Crash occurred on Thread named 'main'
Unix Time : 1733280133615
LocalTime : 2024年12月4日 10:42:13

ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = V2172A
SECURITY_PATCH = 2024-08-01
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = vivo
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = vivo
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = eng.compil.20240925.115627


Error Message : Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
Error Cause : null
Error StackTrace : 

java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:151)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:144)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:140)
	at com.rk.xededitor.SetupEditor.setLanguage(SetupEditor.kt:111)
	at com.rk.xededitor.SetupEditor.setupLanguage(SetupEditor.kt:47)
	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
	at android.app.Activity.performCreate(Activity.java:8946)
	at android.app.Activity.performCreate(Activity.java:8910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4286)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4458)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2854)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7b114d, Dispatchers.Main.immediate]

 ```

**Comment by RohitKushvaha01** [comment]
> After clicking back, editing is possible, but syntax highlighting is not enabled.
> 
> ``` 
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1733280133615
> LocalTime : 2024年12月4日 10:42:13
> 
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = V2172A
> SECURITY_PATCH = 2024-08-01
> BASE_OS = 
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = vivo
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> brand = vivo
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = eng.compil.20240925.115627
> 
> 
> Error Message : Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:151)
> 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:144)
> 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:140)
> 	at com.rk.xededitor.SetupEditor.setLanguage(SetupEditor.kt:111)
> 	at com.rk.xededitor.SetupEditor.setupLanguage(SetupEditor.kt:47)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
> 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
> 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
> 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
> 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> 	at android.app.Activity.performCreate(Activity.java:8946)
> 	at android.app.Activity.performCreate(Activity.java:8910)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4286)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4458)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2854)
> 	at android.os.Handler.dispatchMessage(Handler.java:108)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:328)
> 	at android.app.ActivityThread.main(ActivityThread.java:9223)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7b114d, Dispatchers.Main.immediate]
> 
>  ```

What is the extension of the file you are editing?

**Comment by Bubble-droid** [comment]
> > After clicking back, editing is possible, but syntax highlighting is not enabled.
> > ```
> > Fatal Crash occurred on Thread named 'main'
> > Unix Time : 1733280133615
> > LocalTime : 2024年12月4日 10:42:13
> > 
> > ACTIVE_CODENAMES = []
> > app_version = 2.8.0
> > device_model = V2172A
> > SECURITY_PATCH = 2024-08-01
> > BASE_OS = 
> > RELEASE = 14
> > MEDIA_PERFORMANCE_CLASS = 0
> > CODENAME = REL
> > manufacturer = vivo
> > RELEASE_OR_CODENAME = 14
> > RELEASE_OR_PREVIEW_DISPLAY = 14
> > KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> > SDK_INT = 34
> > PREVIEW_SDK_FINGERPRINT = REL
> > PREVIEW_SDK_INT = 0
> > SDK = 34
> > brand = vivo
> > supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> > INCREMENTAL = eng.compil.20240925.115627
> > 
> > 
> > Error Message : Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> > Error Cause : null
> > Error StackTrace : 
> > 
> > java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:151)
> > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:144)
> > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:140)
> > 	at com.rk.xededitor.SetupEditor.setLanguage(SetupEditor.kt:111)
> > 	at com.rk.xededitor.SetupEditor.setupLanguage(SetupEditor.kt:47)
> > 	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
> > 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
> > 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
> > 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
> > 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
> > 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
> > 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
> > 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
> > 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
> > 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
> > 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
> > 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> > 	at android.app.Activity.performCreate(Activity.java:8946)
> > 	at android.app.Activity.performCreate(Activity.java:8910)
> > 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
> > 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4286)
> > 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4458)
> > 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> > 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> > 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> > 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2854)
> > 	at android.os.Handler.dispatchMessage(Handler.java:108)
> > 	at android.os.Looper.loopOnce(Looper.java:226)
> > 	at android.os.Looper.loop(Looper.java:328)
> > 	at android.app.ActivityThread.main(ActivityThread.java:9223)
> > 	at java.lang.reflect.Method.invoke(Native Method)
> > 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
> > 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> > 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7b114d, Dispatchers.Main.immediate]
> > ```
> 
> What is the extension of the file you are editing?
I encountered this issue when trying to edit .sh, .json, and .yaml files. I'm not sure if I made myself clear, but the problem is that when I open the file directly within the Karbon app, it works fine—no errors and syntax highlighting works as expected. The issue mainly arises when I select Karbon from another application to edit the file; that’s when the error occurs.

**Comment by Bubble-droid** [comment]
> > > > After clicking back, editing is possible, but syntax highlighting is not enabled.
> > > > ```
> > > > Fatal Crash occurred on Thread named 'main'
> > > > Unix Time : 1733280133615
> > > > LocalTime : 2024年12月4日 10:42:13
> > > > 
> > > > ACTIVE_CODENAMES = []
> > > > app_version = 2.8.0
> > > > device_model = V2172A
> > > > SECURITY_PATCH = 2024-08-01
> > > > BASE_OS = 
> > > > RELEASE = 14
> > > > MEDIA_PERFORMANCE_CLASS = 0
> > > > CODENAME = REL
> > > > manufacturer = vivo
> > > > RELEASE_OR_CODENAME = 14
> > > > RELEASE_OR_PREVIEW_DISPLAY = 14
> > > > KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> > > > SDK_INT = 34
> > > > PREVIEW_SDK_FINGERPRINT = REL
> > > > PREVIEW_SDK_INT = 0
> > > > SDK = 34
> > > > brand = vivo
> > > > supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> > > > INCREMENTAL = eng.compil.20240925.115627
> > > > 
> > > > 
> > > > Error Message : Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> > > > Error Cause : null
> > > > Error StackTrace : 
> > > > 
> > > > java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@7fdec61 scope name not found
> > > > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:151)
> > > > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:144)
> > > > 	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:140)
> > > > 	at com.rk.xededitor.SetupEditor.setLanguage(SetupEditor.kt:111)
> > > > 	at com.rk.xededitor.SetupEditor.setupLanguage(SetupEditor.kt:47)
> > > > 	at com.rk.xededitor.SimpleEditor.SimpleEditor$handleIntent$3.invokeSuspend(SimpleEditor.kt:200)
> > > > 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > > > 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
> > > > 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
> > > > 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
> > > > 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
> > > > 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
> > > > 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
> > > > 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
> > > > 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
> > > > 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
> > > > 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.kt:200)
> > > > 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.kt:95)
> > > > 	at android.app.Activity.performCreate(Activity.java:8946)
> > > > 	at android.app.Activity.performCreate(Activity.java:8910)
> > > > 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
> > > > 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4286)
> > > > 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4458)
> > > > 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> > > > 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> > > > 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> > > > 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2854)
> > > > 	at android.os.Handler.dispatchMessage(Handler.java:108)
> > > > 	at android.os.Looper.loopOnce(Looper.java:226)
> > > > 	at android.os.Looper.loop(Looper.java:328)
> > > > 	at android.app.ActivityThread.main(ActivityThread.java:9223)
> > > > 	at java.lang.reflect.Method.invoke(Native Method)
> > > > 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
> > > > 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> > > > 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7b114d, Dispatchers.Main.immediate]
> > > > ```
> > > 
> > > 
> > > What is the extension of the file you are editing?
> > > I encountered this issue when trying to edit .sh, .json, and .yaml files. I'm not sure if I made myself clear, but the problem is that when I open the file directly within the Karbon app, it works fine—no errors and syntax highlighting works as expected. The issue mainly arises when I select Karbon from another application to edit the file; that’s when the error occurs.
> 
> I believe this issue has already been fixed in the action builds (testing). Please try updating to the testing build and let me know if the issue still exists.
>
>I tried the latest build, but the issue still persists. I’ve posted a screen recording in the Telegram group to show the crash process.

**Comment by RohitKushvaha01** [comment]
@Bubble-droid try this new commit

**Comment by Bubble-droid** [comment]
> @Bubble-droid try this new commit尝试这个新提交

>> The issue has been resolved well. Thank you!
