### ISSUE TITLE
Crash Report - Error when opening any file

### ISSUE THREAD

**Issue by krazy-j** [Xed-Editor/Xed-Editor#358]
After opening any file, this error repeatedly pops up every 1 or 2 seconds.
``` 
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-4'
Unix Time : 1733581250766
LocalTime : Dec 7, 2024 08:20:50

ALL_CODENAMES = [REL]
ACTIVE_CODENAMES = []
app_version = 2.8.0
device_model = Pixel 6
MIN_SUPPORTED_TARGET_SDK_INT = 28
RESOURCES_SDK_INT = 35
SECURITY_PATCH = 2024-12-01
BASE_OS = 
RELEASE = 15
MEDIA_PERFORMANCE_CLASS = 31
CODENAME = REL
manufacturer = Google
RELEASE_OR_CODENAME = 15
RELEASE_OR_PREVIEW_DISPLAY = 15
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
SDK_INT = 35
PREVIEW_SDK_FINGERPRINT = REL
DEVICE_INITIAL_SDK_INT = 31
PREVIEW_SDK_INT = 0
SDK = 35
brand = google
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 2024120400


Error Message : null
Error Cause : java.net.SocketException: socket failed: EACCES (Permission denied)
Error StackTrace : 

java.lang.ExceptionInInitializerError
	at com.rk.xededitor.MainActivity.handlers.MenuItemHandler$updateInternal$2.invokeSuspend(MenuItemHandler.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2647213, Dispatchers.Default]
Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
	at java.net.ServerSocket.createImpl(ServerSocket.java:331)
	at java.net.ServerSocket.getImpl(ServerSocket.java:281)
	at java.net.ServerSocket.bind(ServerSocket.java:399)
	at java.net.ServerSocket.<init>(ServerSocket.java:259)
	at java.net.ServerSocket.<init>(ServerSocket.java:151)
	at com.rk.runner.commonUtils.getAvailablePort(commonUtils.kt:95)
	at com.rk.runner.runners.web.html.HtmlRunner.<init>(HtmlRunner.kt:15)
	at com.rk.runner.Runner.<clinit>(Runner.kt:43)
	... 13 more

 ```

**Comment by RohitKushvaha01** [comment]
> After opening any file, this error repeatedly pops up every 1 or 2 seconds.
> ``` 
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-4'
> Unix Time : 1733581250766
> LocalTime : Dec 7, 2024 08:20:50
> 
> ALL_CODENAMES = [REL]
> ACTIVE_CODENAMES = []
> app_version = 2.8.0
> device_model = Pixel 6
> MIN_SUPPORTED_TARGET_SDK_INT = 28
> RESOURCES_SDK_INT = 35
> SECURITY_PATCH = 2024-12-01
> BASE_OS = 
> RELEASE = 15
> MEDIA_PERFORMANCE_CLASS = 31
> CODENAME = REL
> manufacturer = Google
> RELEASE_OR_CODENAME = 15
> RELEASE_OR_PREVIEW_DISPLAY = 15
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, VanillaIceCream, KitkatWatch, Base11, Eclair}
> SDK_INT = 35
> PREVIEW_SDK_FINGERPRINT = REL
> DEVICE_INITIAL_SDK_INT = 31
> PREVIEW_SDK_INT = 0
> SDK = 35
> brand = google
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 2024120400
> 
> 
> Error Message : null
> Error Cause : java.net.SocketException: socket failed: EACCES (Permission denied)
> Error StackTrace : 
> 
> java.lang.ExceptionInInitializerError
> 	at com.rk.xededitor.MainActivity.handlers.MenuItemHandler$updateInternal$2.invokeSuspend(MenuItemHandler.kt:60)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 	at android.os.Handler.handleCallback(Handler.java:959)
> 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 	at android.os.Looper.loopOnce(Looper.java:232)
> 	at android.os.Looper.loop(Looper.java:317)
> 	at android.app.ActivityThread.main(ActivityThread.java:8744)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2647213, Dispatchers.Default]
> Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
> 	at java.net.ServerSocket.createImpl(ServerSocket.java:331)
> 	at java.net.ServerSocket.getImpl(ServerSocket.java:281)
> 	at java.net.ServerSocket.bind(ServerSocket.java:399)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:259)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:151)
> 	at com.rk.runner.commonUtils.getAvailablePort(commonUtils.kt:95)
> 	at com.rk.runner.runners.web.html.HtmlRunner.<init>(HtmlRunner.kt:15)
> 	at com.rk.runner.Runner.<clinit>(Runner.kt:43)
> 	... 13 more
> 
>  ```

Update to latest testing Build

https://github.com/Xed-Editor/Xed-Editor/actions/runs/12213461094#artifacts

Make sure to only choose **Release** build
