### ISSUE TITLE
Karbon is suggested to open everything

### ISSUE THREAD

**Issue by Orzomaxx** [Xed-Editor/Xed-Editor#362]
**Describe the bug**
Karbon is suggested to open everything: .apk files, videos, music, photos and everything else

**To Reproduce**
For example: try to install .apk file

**Expected behavior**
Karbon will be suggested only for files with `text/*` MIME types (and maybe `application/*`), not for everything

**complete the following information):**
 - Device: Tecno Camon 20 Pro 5G
 - OS: HiOS 14.0.0
 - Android 14

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> Karbon is suggested to open everything: .apk files, videos, music, photos and everything else
> 
> **To Reproduce**
> For example: try to install .apk file
> 
> **Expected behavior**
> Karbon will be suggested only for files with `text/*` MIME types (and maybe `application/*`), not for everything
> 
> **complete the following information):**
>  - Device: Tecno Camon 20 Pro 5G
>  - OS: HiOS 14.0.0
>  - Android 14

It's not a bug, it's a feature.
Sometimes, a text file has an odd extension or no extension at all, making it frustrating when no text editor appears for editing.

**Comment by Orzomaxx** [comment]
If file has wrong extension, that means you should do either:
1. Rename file, so its extension matches its contents.
2. Open file directly from Karbon, as there is no limits.
3. Use file explorer with support for "`Open as`" functionality, like X-Plore.
4. If this somehow is not possible (e.g. readonly access via SAF, opening files in Karbon is broken, good file explorer is not installed), at least you can save it somewhere, rename and then open.

There is always a way to open files with strange extensions.

Anyway, can you make this functionality disableable?
Because if app wants to open everything, then app will try to open even what should not be opened in it (for example - .exe files)
This is even worse when there is only 1 such app in system - it will open such files `automatically`
