### ISSUE TITLE
Gender biased and sexual slavery texts in Chinese (zh) translation

### ISSUE THREAD

**Issue by oldherl** [Xed-Editor/Xed-Editor#364]
**Describe the bug**
The following texts in Chinese (zh) translation are inappropriate.

**To Reproduce**
https://github.com/Xed-Editor/Xed-Editor/blob/bdd818e9a0ab12e43c6d4787e996195b4b74e2a6/core/resources/src/main/res/values-zh/strings.xml#L52
> 你还有文件没保存呢，哥哥！

Which literally means
> You have unsaved files, brother!

It implies that the user is a male.

https://github.com/Xed-Editor/Xed-Editor/blob/bdd818e9a0ab12e43c6d4787e996195b4b74e2a6/core/resources/src/main/res/values-zh/strings.xml#L142
> 求求大人您在接下来弹出的系统菜单里选择准许我获取您身体的存储权限，同意我这个小小要求，辛苦了主人~

Which literally means
> Please allow me to get storage permission for your body in the upcoming popup menu, master (goshujin-sama) ! This is only a tiny request compared to your hard work, master!

The language implies sexual slavery.

There are more inappropriate texts in the zh translation but I'm not listing them all here.

**Expected behavior**
The translation should not add such inappropriate language completely unrelated to the original meaning. One possible translation for the above two texts are:
> 你还有尚未保存的文件

and
> 请在接下来弹出的系统菜单里批准获取存储权限

**Screenshots**

**complete the following information):**
 - Device: [e.g. Redmi 5A]
 - OS: [e.g. MIUI 11]
 - Android Version [e.g. Android 10]

**logcat output/logcat.txt(if applicable)**

**Additional context**
I understand that those translations are from Weblate. I suggest to warn and/or suspend the contribution from this account, if possible.

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> The following texts in Chinese (zh) translation are inappropriate.
> 
> **To Reproduce**
> https://github.com/Xed-Editor/Xed-Editor/blob/bdd818e9a0ab12e43c6d4787e996195b4b74e2a6/core/resources/src/main/res/values-zh/strings.xml#L52
> > 你还有文件没保存呢，哥哥！
> 
> Which literally means
> > You have unsaved files, brother!
> 
> It implies that the user is a male.
> 
> https://github.com/Xed-Editor/Xed-Editor/blob/bdd818e9a0ab12e43c6d4787e996195b4b74e2a6/core/resources/src/main/res/values-zh/strings.xml#L142
> > 求求大人您在接下来弹出的系统菜单里选择准许我获取您身体的存储权限，同意我这个小小要求，辛苦了主人~
> 
> Which literally means
> > Please allow me to get storage permission for your body in the upcoming popup menu, master (goshujin-sama) ! This is only a tiny request compared to your hard work, master!
> 
> The language implies sexual slavery.
> 
> There are more inappropriate texts in the zh translation but I'm not listing them all here.
> 
> **Expected behavior**
> The translation should not add such inappropriate language completely unrelated to the original meaning. One possible translation for the above two texts are:
> > 你还有尚未保存的文件
> 
> and
> > 请在接下来弹出的系统菜单里批准获取存储权限
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **complete the following information):**
>  - Device: [e.g. Redmi 5A]
>  - OS: [e.g. MIUI 11]
>  - Android Version [e.g. Android 10]
> 
> **logcat output/logcat.txt(if applicable)**
> 
> 
> **Additional context**
> I understand that those translations are from Weblate. I suggest to warn and/or suspend the contribution from this account, if possible.
> 

Thank you for bringing this issue to my attention. I have addressed it by removing the translations.

**Comment by Thisisnotgoingpublished** [comment]
Yeah, I deserve that. Well, so then who's gonna translate it again, please do it now soon

**Comment by Thisisnotgoingpublished** [comment]
Hi Rohit,

I wanted to apologize for the style of the wording in pull request #350. I realized that not everyone may find it suitable, and I deeply regret any inconvenience this may have caused.

Please let me know if you think it's best to revise the PR or if you'd prefer I make any changes.

Thank you for your understanding.

Best regards,

**Comment by Thisisnotgoingpublished** [comment]
那就用AI吧，AI的话就比较中立了，格式也非常标准，也比我强很多。其他的你看着改吧。我睡了。

**Comment by Thisisnotgoingpublished** [comment]
> > 那就用AI吧，AI的话就比较中立了，格式也非常标准，也比我强很多。其他的你看着改吧。我睡了。
> 
> @Thisisnotgoingpublished Hi, could you translate https://github.com/FooIbar/EhViewer with that amazing tone? Due to NSFW we cannot use weblate. Btw we want to keep original Chinese translation and provide that as alternative. Sorry for that off-topic but I can't get in touch with you amazing translator.

@revonateB0T 
Thanks for the offer, and I appreciate your review, but...

Sorry, I’ve been reading about the Mandarin communities this morning, and I've come to realize just how vast they are. I also went through oldherl's bio and blogs, and they really made me reflect. I feel like I'm not as impressive as they are—just a small, unknown, insignificant figure.

To avoid offending the general public, I’ve decided not to engage in such activities again. I’ve also promised the author of this project that I won’t do something like this again.

That being said, I’ll admit I’m being a little stubborn here—I think you might actually deserve a bad literal translation, but hey, let the machines do the magic.

I spent the entire weekend working on this, and now it’s all gone and labeled as spam.

Honestly, I’m not in the best mood these days.

As for the new translation I did in an hour by simply copying and pasting, aside from my keyboard, I think everyone is happy with the result.

If you’d like, you can try teaching AI to generate the content you need by feeding it specific requirements.
