### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Xed-Editor/Xed-Editor#368]
**Describe the bug**
 There are binaries in https://github.com/Xed-Editor/Xed-Editor/tree/v2.9.0/core/wasm3/src/main/cpp. Could you please add them to gitignore? Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**complete the following information):**
 - Device: [e.g. Redmi 5A]
 - OS: [e.g. MIUI 11]
 - Android Version [e.g. Android 10]

**logcat output/logcat.txt(if applicable)**

**Additional context**

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** There are binaries in https://github.com/Xed-Editor/Xed-Editor/tree/v2.9.0/core/wasm3/src/main/cpp. Could you please add them to gitignore? Thanks!
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **complete the following information):**
> 
> * Device: [e.g. Redmi 5A]
> * OS: [e.g. MIUI 11]
> * Android Version [e.g. Android 10]
> 
> **logcat output/logcat.txt(if applicable)**
> 
> **Additional context** Add any other context about the problem here.

done 👍

**Comment by linsui** [comment]
Those files need to be removed manually first. And please only ignore https://github.com/Xed-Editor/Xed-Editor/tree/v2.9.0/core/wasm3/src/main/cpp/m3/CMakeFiles and https://github.com/Xed-Editor/Xed-Editor/blob/v2.9.0/core/wasm3/src/main/cpp/m3/libm3.a. Other files are still needed.

**Comment by RohitKushvaha01** [comment]
> Those files need to be removed manually first. And please only ignore https://github.com/Xed-Editor/Xed-Editor/tree/v2.9.0/core/wasm3/src/main/cpp/m3/CMakeFiles and https://github.com/Xed-Editor/Xed-Editor/blob/v2.9.0/core/wasm3/src/main/cpp/m3/libm3.a. Other files are still needed.

I think I should remove the module entirely and recreate the release. That module is not used by the app.

**Comment by linsui** [comment]
That also works if it's not used. :)

**Comment by RohitKushvaha01** [comment]
> That also works if it's not used. :)

I recreated the release with a completely new commit and removed the WASM module.

**Comment by linsui** [comment]
Thanks!
