### ISSUE TITLE
Issues with fastlane changelogs

### ISSUE THREAD

**Issue by IzzySoft** [Xed-Editor/Xed-Editor#370]
Please keep in mind that Fastlane per-release changelogs are limited to 500 chars each, everything beyond that will simply be truncated:

```
! com.rk.xededitor/en-US/changelogs/33.txt has 700 chars
! com.rk.xededitor/en-US/changelogs/35.txt has 924 chars
! com.rk.xededitor/en-US/changelogs/36.txt has 1123 chars
```

Before you ask: not my definition, Fastlane standard :man_shrugging:

**Comment by RohitKushvaha01** [comment]
> Please keep in mind that Fastlane per-release changelogs are limited to 500 chars each, everything beyond that will simply be truncated:
> 
> ```
> ! com.rk.xededitor/en-US/changelogs/33.txt has 700 chars
> ! com.rk.xededitor/en-US/changelogs/35.txt has 924 chars
> ! com.rk.xededitor/en-US/changelogs/36.txt has 1123 chars
> ```
> 
> Before you ask: not my definition, Fastlane standard :man_shrugging: 

Understood 👍

**Comment by IzzySoft** [comment]
Understanding is a good first step 😉 But something's amiss, as this month's quality check reports:

```
! build/com.rk.xededitor/metadata/en-US/changelogs/41.txt has 600 chars
! build/com.rk.xededitor/metadata/en-US/changelogs/61.txt has 1045 chars
! build/com.rk.xededitor/metadata/en-US/changelogs/62.txt has 1045 chars
```

**Comment by IzzySoft** [comment]
I've now deleted them all at our end, @RohitKushvaha01 – tired of getting the same warning each month, when our quality check runs 🙈 Will disable fetching them if it cannot be solved.
