### ISSUE TITLE
terminal: allow to use git, maybe even use apt to install packages

### ISSUE THREAD

**Issue by farfromrefug** [Xed-Editor/Xed-Editor#371]
i like the fact that you can handle git directly in the app. But sometimes it is better to use git command like to handle complex cases.
At first i thought about using termux as a separated app. But as you already integrate termux inside the app it would be awesome to have the git command there:
* allow to access git command in terminal
* use credential entered in the app
* if we cant use git credential entered in the app then we would need to be able to install gh/openssh through the terminal to login to github

**Comment by RohitKushvaha01** [comment]
> i like the fact that you can handle git directly in the app. But sometimes it is better to use git command like to handle complex cases.
> At first i thought about using termux as a separated app. But as you already integrate termux inside the app it would be awesome to have the git command there:
> * allow to access git command in terminal
> * use credential entered in the app
> * if we cant use git credential entered in the app then we would need to be able to install gh/openssh through the terminal to login to github

Use the latest action build, you can install packages using the "apk" command

**Comment by farfromrefug** [comment]
@RohitKushvaha01 you are too fast thank you ! Just to be sure. We agree it won't use the same credentials as within the app right ? With the terminal I have  to use git ssh key. Can in use it too with karbon ? (Cloning, gît menu commands)

**Comment by RohitKushvaha01** [comment]
> @RohitKushvaha01 you are too fast thank you ! Just to be sure. We agree it won't use the same credentials as within the app right ? With the terminal I have  to use git ssh key. Can in use it too with karbon ? (Cloning, gît menu commands)

Karbon creates .gitconfig for storing username and email
And .git-credentials for the url/password

So the git command in terminal can also use these

**Comment by farfromrefug** [comment]
@RohitKushvaha01 I tried your new version and indeed I get gît.
Now I see that we cant install using apt.
Instead of asking you to add more and more packages to the integrated termux, coud we instead have an option to use the termux app when clicking on the terminal button?
Maybe it could even open a session in the correct folder using intent? Even crazier idea maybe it could use a project named session so that it always open the same session ?

Might be a better solution because we could use all the features of termux. Right now the integrated terminal is pretty limited.

**Comment by RohitKushvaha01** [comment]
> @RohitKushvaha01 I tried your new version and indeed I get gît.
> Now I see that we cant install using apt.
> Instead of asking you to add more and more packages to the integrated termux, coud we instead have an option to use the termux app when clicking on the terminal button?
> Maybe it could even open a session in the correct folder using intent? Even crazier idea maybe it could use a project named session so that it always open the same session ?
> 
> Might be a better solution because we could use all the features of termux. Right now the integrated terminal is pretty limited.

Use apk command to install new packages

**Comment by farfromrefug** [comment]
@RohitKushvaha01 tok tried apt.and pkg but not apk. 
Still think it would be really nice to be able.to usé termux directly. 
For example.we can't style font colors in the integrated.termux. using termux we could also use floating window ans any other termux plugin.
One last benefit would be to use the same zshrc , git credentials, ...
