### ISSUE TITLE
"Auto save" is turned off and app still saves on exit

### ISSUE THREAD

**Issue by GitAlasGo** [Xed-Editor/Xed-Editor#374]
The "Auto save" feature is turned off, as expected it doesn't save, but when you go into the recent apps and close the karbon app, and then go back into the files, you will see that it got saved.

This is making people lose their work, You are misleading them by the "Auto save" when it is literally auto saving on exit.

Acode editor doesn't have this problem.

**Comment by RohitKushvaha01** [comment]
> The "Auto save" feature is turned off, as expected it doesn't save, but when you go into the recent apps and close the karbon app, and then go back into the files, you will see that it got saved.
> 
> This is making people lose their work, You are misleading them by the "Auto save" when it is literally auto saving on exit.
> 
> Acode editor doesn't have this problem.

https://github.com/Xed-Editor/Xed-Editor/actions/runs/12423451442#artifacts

This should fix it
