### ISSUE TITLE
Error "Job was cancelled"

### ISSUE THREAD

**Issue by xderrisk** [Xed-Editor/Xed-Editor#386]
Al girar la pantalla dentro de la aplicación, no se permite la ejecución de código. Esto interrumpe la funcionalidad esperada de la aplicación.

Pasos para reproducir el comportamiento:

1. Abre la aplicación.

2. Crea un script que permita la ejecución de código.

3. Gira la pantalla al modo horizontal o vertical.

4. Aparece el mensaje "Job was cancelled"

5. El boton de ejecutar código no responde.

Comportamiento esperado
La ejecución del código se debe realizar sin interrupciones, incluso cuando se gira la pantalla.

Capturas de pantalla
![Screenshot_20241220_195346_Karbon.jpg](https://github.com/user-attachments/assets/dbd0b2d3-751d-48a5-be04-22720bb58565)

Dispositivo: Samsung A15

SO: One UI 6.1

Versión de Android: Android 14

Contexto adicional
El problema parece estar relacionado con el manejo de los cambios de configuración por parte de la aplicación, como la rotación de la pantalla.

**Comment by RohitKushvaha01** [comment]
> Al girar la pantalla dentro de la aplicación, no se permite la ejecución de código. Esto interrumpe la funcionalidad esperada de la aplicación.
> 
> Pasos para reproducir el comportamiento:
> 
> 1. Abre la aplicación.
> 
> 2. Crea un script que permita la ejecución de código.
> 
> 3. Gira la pantalla al modo horizontal o vertical.
> 
> 4. Aparece el mensaje "Job was cancelled"
> 
> 5. El boton de ejecutar código no responde.
> 
> Comportamiento esperado
> La ejecución del código se debe realizar sin interrupciones, incluso cuando se gira la pantalla.
> 
> Capturas de pantalla
> ![Screenshot_20241220_195346_Karbon.jpg](https://github.com/user-attachments/assets/dbd0b2d3-751d-48a5-be04-22720bb58565)
> 
> Dispositivo: Samsung A15
> 
> SO: One UI 6.1
> 
> Versión de Android: Android 14
> 
> Contexto adicional
> El problema parece estar relacionado con el manejo de los cambios de configuración por parte de la aplicación, como la rotación de la pantalla.

That's completely normal behavior, it doesn't affect the usability of the app in any way

**Comment by xderrisk** [comment]
en la versión 2.9.0 ya no sucede el error, pero tuve que instalar termux
